[package]
name = "azalea-health"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-client = "0.6.0"
azalea-ecs = "0.6.0"
derive_more = "0.99.17"
tiny_http = "0.12.0"
